In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_parquet("train.parquet")
df2=pd.read_parquet("test.parquet")

In [3]:
#Viewing the dataset.
df1.head(30)

                             Patient-Uid       Date           Incident
0   a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2019-03-09  PRIMARY_DIAGNOSIS
1   a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f 2015-05-16  PRIMARY_DIAGNOSIS
3   a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f 2018-01-30     SYMPTOM_TYPE_0
4   a0dc950b-1c7c-11ec-b6ec-16262ee38c7f 2015-04-22        DRUG_TYPE_0
8   a0dc9543-1c7c-11ec-bb63-16262ee38c7f 2016-06-18        DRUG_TYPE_1
9   a0dc9577-1c7c-11ec-8b4d-16262ee38c7f 2019-12-16        DRUG_TYPE_1
11  a0dc95c6-1c7c-11ec-8e77-16262ee38c7f 2020-02-07        DRUG_TYPE_1
12  a0dc95f9-1c7c-11ec-b968-16262ee38c7f 2019-08-01        DRUG_TYPE_1
14  a0dc962a-1c7c-11ec-8a51-16262ee38c7f 2017-06-20        DRUG_TYPE_1
16  a0dc9659-1c7c-11ec-a91e-16262ee38c7f 2015-11-25        DRUG_TYPE_2
17  a0dc9689-1c7c-11ec-9ca7-16262ee38c7f 2016-08-07        TEST_TYPE_0
19  a0dc96ca-1c7c-11ec-89e9-16262ee38c7f 2016-09-14        DRUG_TYPE_2
20  a0dc96fb-1c7c-11ec-82ed-16262ee38c7f 2018-11-02        DRUG_TYPE_3
21  a0dc972c-1c7c-11ec-a850-16262ee38c7f 2015-07-04        DRUG_TYPE_1
24  a0dc975b-1c7c-11ec-bb4a-16262ee38c7f 2019-04-03        DRUG_TYPE_2
25  a0dc978b-1c7c-11ec-9956-16262ee38c7f 2018-03-01        DRUG_TYPE_3
26  a0dc97bd-1c7c-11ec-a9d4-16262ee38c7f 2015-08-02  PRIMARY_DIAGNOSIS
27  a0dc97ee-1c7c-11ec-b241-16262ee38c7f 2016-01-27        DRUG_TYPE_4
28  a0dc981e-1c7c-11ec-b4aa-16262ee38c7f 2017-09-21        DRUG_TYPE_5
30  a0dc984d-1c7c-11ec-b4de-16262ee38c7f 2018-01-13     SYMPTOM_TYPE_0
31  a0dc987c-1c7c-11ec-b249-16262ee38c7f 2015-05-06        DRUG_TYPE_0
34  a0dc98ae-1c7c-11ec-82ad-16262ee38c7f 2018-10-05        DRUG_TYPE_6
36  a0dc98e7-1c7c-11ec-9cc8-16262ee38c7f 2019-11-29        DRUG_TYPE_8
38  a0dc9919-1c7c-11ec-8049-16262ee38c7f 2016-07-06        DRUG_TYPE_6
41  a0dc9950-1c7c-11ec-818a-16262ee38c7f 2017-04-05        DRUG_TYPE_7
44  a0dc9982-1c7c-11ec-be1a-16262ee38c7f 2015-07-28        DRUG_TYPE_1
46  a0dc99b3-1c7c-11ec-856e-16262ee38c7f 2018-01-28        DRUG_TYPE_5
48  a0dc99e2-1c7c-11ec-a822-16262ee38c7f 2019-12-12        DRUG_TYPE_0
49  a0dc9a12-1c7c-11ec-a92d-16262ee38c7f 2019-01-03        DRUG_TYPE_0
51  a0dc9a42-1c7c-11ec-842c-16262ee38c7f 2016-07-02     SYMPTOM_TYPE_1

In [4]:
# dROPPING THE DATE AS IT DOESNOT HAVE SIGNIFICANT ROLE.
df11=df1.drop('Date',axis=1)

In [5]:
df11.head(2)

                            Patient-Uid           Incident
0  a0db1e73-1c7c-11ec-ae39-16262ee38c7f  PRIMARY_DIAGNOSIS
1  a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f  PRIMARY_DIAGNOSIS

In [6]:
# Doing OneHotEncoding:
df1_data=pd.get_dummies(df1['Incident'], drop_first=True)

In [7]:
# Concating the datasets.
df12=pd.concat([df11,df1_data],axis=1)

In [8]:
# Dropping the Incident feature as it now Encoded.
df13=df12.drop('Incident',axis=1)

In [9]:
df13.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# Values of Traget Variable.
df13['TARGET DRUG'].value_counts()

0    3153650
1      67218
Name: TARGET DRUG, dtype: int64

In [11]:
# Extracting the target 0 values
df10=df13[df13['TARGET DRUG']==0]

In [12]:
# Extracting the target 1 values
df101=df13[df13['TARGET DRUG']==1]

In [13]:
# sampling the dataset.
df100=df10.sample(n=67218)

In [14]:
# Grouping the dataset of target 0 by patient uid
df100_data=df100.groupby(by='Patient-Uid',as_index=False).mean()

In [15]:
df100_data.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
# changeing the datatype of target value.
df100_data['TARGET DRUG']=df100_data['TARGET DRUG'].astype(int)

In [17]:
df100_data.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,0.0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# Grouping the dataset of target 1 by patient uid
df101_data=df101.groupby(by='Patient-Uid',as_index=False).mean()

In [19]:
df101_data.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0e9c384-1c7c-11ec-81a0-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,a0e9c3b3-1c7c-11ec-ae8e-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
df101_data1=df101_data.drop('Patient-Uid',axis=1)

In [21]:
df101_data01=df101_data1.apply(lambda x:x.astype(float))

In [22]:
df101_data11=pd.concat([pd.DataFrame(df101_data['Patient-Uid']),df101_data01],axis=1)

In [23]:
# Concating the data to form new dataset for taining purspose.
df1_data=pd.concat([df100_data,df101_data11],axis=0)

In [24]:
# splitting the dataset to independent and dependent variable
x_df1=df1_data.drop(['TARGET DRUG','DRUG_TYPE_18'],axis=1)

In [25]:
x_df11=x_df1.drop('Patient-Uid',axis=1)

In [26]:
# splitting the dataset to independent and dependent variable
y_df1=df1_data['TARGET DRUG']

In [27]:
df2.head(30)

                             Patient-Uid       Date           Incident
0   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08     SYMPTOM_TYPE_0
1   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17        DRUG_TYPE_0
2   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01        DRUG_TYPE_2
3   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05        DRUG_TYPE_1
4   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-11-04     SYMPTOM_TYPE_0
6   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09  PRIMARY_DIAGNOSIS
7   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-07-07        DRUG_TYPE_8
8   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08        TEST_TYPE_0
9   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2019-05-21        DRUG_TYPE_0
10  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-06-23        DRUG_TYPE_7
11  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-22        DRUG_TYPE_8
12  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08        DRUG_TYPE_0
13  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17        DRUG_TYPE_8
14  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-09-12  PRIMARY_DIAGNOSIS
15  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09        DRUG_TYPE_0
16  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-21        DRUG_TYPE_8
17  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-01        DRUG_TYPE_8
18  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-21  PRIMARY_DIAGNOSIS
19  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-06-07        DRUG_TYPE_8
20  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01  PRIMARY_DIAGNOSIS
21  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08  PRIMARY_DIAGNOSIS
22  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09        DRUG_TYPE_8
23  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05        DRUG_TYPE_0
24  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-09-27        DRUG_TYPE_8
25  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-09-12  PRIMARY_DIAGNOSIS
26  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01  PRIMARY_DIAGNOSIS
27  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09  PRIMARY_DIAGNOSIS
28  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2019-01-02        DRUG_TYPE_1
29  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-09-27  PRIMARY_DIAGNOSIS
30  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08       DRUG_TYPE_11

In [28]:
df21=df2.drop('Date',axis=1)

In [29]:
df21.head(2)

                            Patient-Uid        Incident
0  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f  SYMPTOM_TYPE_0
1  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_0

In [30]:
# Doing OneHotEncoding:
df2_data=pd.get_dummies(df2['Incident'],drop_first=True)

In [31]:
# Concating the datasets.
df22=pd.concat([df21,df2_data],axis=1)

In [32]:
# Dropping the Incident feature as it now Encoded.
df23=df22.drop('Incident',axis=1)

In [33]:
df23.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
df23.shape

(1065524, 55)

In [35]:
# Grouping the dataset of df2 by patient uid.
df2_data=df23.groupby('Patient-Uid',as_index=False).mean()

In [36]:
# Viewing the Dataset.
df2_data.sample(4)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
2954,a0fc1e1e-1c7c-11ec-9f24-16262ee38c7f,0.092784,0.0,0.061856,0.0,0.0,0.0,0.0,0.0,0.0,...,0.051546,0.020619,0.0,0.020619,0.010309,0.030928,0.0,0.0,0.0,0.0
5936,a0fe547e-1c7c-11ec-b809-16262ee38c7f,0.241379,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.034483,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
8385,a100232a-1c7c-11ec-acc0-16262ee38c7f,0.129630,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.018519,0.000000,0.0,0.0,0.0,0.0
5895,a0fe4cd7-1c7c-11ec-b5d3-16262ee38c7f,0.088889,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.033333,0.000000,0.0,0.000000,0.000000,0.033333,0.0,0.0,0.0,0.0

In [37]:
df2_data.shape

(11482, 55)

In [38]:
x_df2_data=df2_data.drop('Patient-Uid',axis=1)

In [39]:
x_df2_data.shape

(11482, 54)

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [41]:
lr=LogisticRegression()
model_df1=lr.fit(x_df11,y_df1)

In [42]:
predict_df1=lr.predict(x_df11)
score=accuracy_score(predict_df1,y_df1)
score

0.9752221095022903

In [43]:
predict_df2=lr.predict(x_df2_data).astype(int)

In [44]:
data=pd.DataFrame(predict_df2)
data1=pd.concat([pd.DataFrame(df2_data['Patient-Uid']),data],axis=1)

In [45]:
data1.to_excel("Sample_submission.xlsx")